- name: Commit e Push delle modifiche
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          # Il comando || exit 0 evita che la Action fallisca se non ci sono foto da comprimere
          git commit -m "Compressione automatica immagini 01" || exit 0
          
          # 1. Recupera le modifiche che sono online mentre la Action girava
          git fetch origin main
          
          # 2. Sincronizza i cambiamenti (rebase) per evitare il conflitto
          git pull --rebase origin main
          
          # 3. Ora il push funzionerà senza errori
          git push origin main
