name: Watermark TEST

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  watermark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Apply TEXT watermark
        run: |
          find "./AUTO 3" -type f \( -iname "*.jpg" -o -iname "*.png" \) | while read img; do
            echo "Processing: $img"

            magick "$img" \
              -gravity southeast \
              -fill "red" \
              -pointsize 40 \
              -annotate +10+10 "TEST WATERMARK" \
              "$img"
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add -A

          git diff --cached --quiet && echo "NO CHANGES" && exit 0

          git commit -m "test watermark"
          git push
