name: Applica Watermark

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pillow
        run: pip install Pillow

      - name: Esegui Diagnosi e Script
        run: python watermark.py

      - name: Prova a salvare (se ci sono modifiche)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Aggiornamento foto" || echo "Nessuna modifica da salvare"
          git push || echo "Push fallito o non necessario"
