name: Applica Watermark

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pillow
        run: pip install Pillow

      - name: Esegui Script
        run: python watermark.py

      - name: Salva le foto
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Il comando qui sotto non darà errore se la cartella non esiste
          if [ -d "AUTO3_PRONTE" ]; then
            git add AUTO3_PRONTE/
            git commit -m "Watermark aggiunto"
            git push
          else
            echo "La cartella AUTO3_PRONTE non è stata creata. Controlla i log dello script Python sopra."
          fi
